# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'UKHO Windows 2019'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices\\dataservices.csproj'
    feedsToUse: 'select'
  displayName: 'dotnet restore dataservices'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices\\dataservices.csproj'
  displayName: 'dotnet build dataservices'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices.unittests\\dataservices.unittests.csproj'
    feedsToUse: 'select'
  displayName: 'dotnet restore dataservicestests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices.unittests\\dataservices.unittests.csproj'
  displayName: 'dotnet build dataservicestests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices.unittests\\dataservices.unittests.csproj'
  displayName: 'dotnet test dataservicestests'

- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices.apitests\\pom.xml'
    goals: 'test-compile'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'mvn test-compile dataservices.apitests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices\\dataservices.csproj'
    zipAfterPublish: false
    arguments: '--output $(Build.ArtifactStagingDirectory)\\dataservices'
  displayName: 'Publish Solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\\dataservices'
    ArtifactName: 'dataservices'
    publishLocation: 'Container'
  displayName: 'Publish dataservices Artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\\src\\dataservices\\dataservices.apitests\\'
    ArtifactName: 'dataservices.apitests'
    publishLocation: 'Container'
  displayName: 'Publish dataservices.apitests Artifact'    