trigger:
- master

stages:
- stage: Build
  jobs:
    - job: RestoreBuildAndDeploy
      pool: "UKHO Windows 2019"

      workspace:
          clean: all

      steps:
      - task: VSBuild@1
        inputs:
          solution: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase\\WorkflowDatabase.sqlproj'
          msbuildArgs: /t:Build;Publish /p:SqlPublishProfilePath=WorkflowDatabase.LocalDb.publish.xml
        displayName: 'Build WorkflowDatabase and publish to LocalDb'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase.Tests\\WorkflowDatabase.Tests.csproj'
        displayName: 'dotnet test LocalDb instance of database'

      - task: VSBuild@1
        inputs:
          solution: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase\\WorkflowDatabase.sqlproj'
        displayName: 'Build WorkflowDatabase Dacpac'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase\\bin\\debug\\WorkflowDatabase.dacpac'
          ArtifactName: 'workflowdatabase'
          publishLocation: 'Container'
        displayName: 'Publish WorkflowDatabase'

- stage: DeployDev
  dependsOn: Build
  jobs:
    - deployment: DeployWorkflowDatabaseDev
      displayName: Deploy WorkflowDatabase
      pool: "NautilusRelease"
      environment: 'TaskmanagerDev'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  # azureSubscription: 'TM2 Dev/Test Sub Dev RG'
                  azureSubscription: 'SharedServicesPre'
                  ServerName: '$(ServerNameDev)'
                  DatabaseName: '$(DatabaseNameDev)'
                  SqlUsername: '$(SQLUsernameDev)'
                  SqlPassword: '$(SQLPasswordDev)'
                  DacpacFile: '$(Pipeline.Workspace)/workflowdatabase/WorkflowDatabase.dacpac'

- stage: DeployUAT
  dependsOn: Build
  jobs:
    - deployment: DeployWorkflowDatabaseUAT
      displayName: Deploy WorkflowDatabase
      pool: "NautilusRelease"
      environment: 'TaskmanagerUAT'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  # azureSubscription: 'TM2 Dev/Test Sub Dev RG'
                  azureSubscription: 'SharedServicesPre'
                  ServerName: '$(ServerNameUAT)'
                  DatabaseName: '$(DatabaseNameUAT)'
                  SqlUsername: '$(SQL_UsernameBenUAT)'
                  SqlPassword: '$(SQL_PasswordBenUAT)'
                  DacpacFile: '$(Pipeline.Workspace)/workflowdatabase/WorkflowDatabase.dacpac'

- stage: DeployPre
  dependsOn: Build
  jobs:
    - deployment: DeployWorkflowDatabasePre
      displayName: Deploy WorkflowDatabase
      pool: "NautilusRelease"
      environment: 'TaskmanagerPre'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  # azureSubscription: 'TM2 Dev/Test Sub Dev RG'
                  azureSubscription: 'SharedServicesPre'
                  ServerName: '$(ServerNamePre)'
                  DatabaseName: '$(DatabaseNamePre)'
                  SqlUsername: '$(SQLUsernamePre)'
                  SqlPassword: '$(SQLPasswordPre)'
                  DacpacFile: '$(Pipeline.Workspace)/workflowdatabase/WorkflowDatabase.dacpac'
